apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
  namespace: example-namespace
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "14"
            memory: "128Mi"
          limits:
            cpu: "15"
            memory: "256Mi"