---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-pythonapp
  namespace: hpa
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "10M", "--timeout", "300s"]
        # image: vinaay/pythonapp:v2
        # ports:
        # - containerPort: 8002
        resources:
          requests:
            cpu: "20m"
            memory: "35Mi"
          limits:
            cpu: "20m"
            memory: "40Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-pythonapp
#   namespace: hpa
#   labels:
#     app: pythonapp
# spec:
#   type: ClusterIP
#   selector:
#     app: pythonapp
#   ports:
#     - protocol: TCP
#       port: 8002
#       targetPort: 8002
